SELECT
	DISTINCT
    
    # cleaning manufacturers
	CASE
        WHEN LOWER(TRIM(Manufacturer)) = 'vycon' THEN 'vy con'
        WHEN LOWER(TRIM(Manufacturer)) = 'welchallyn' THEN 'welch allyn'
        WHEN LOWER(TRIM(Manufacturer)) = 'wipak medical (steriking)' THEN 'wipak medical'
        WHEN LOWER(TRIM(Manufacturer)) = 'no manufacturer listed' THEN 'unknown'
        WHEN LOWER(TRIM(Manufacturer)) = 'unnamed' THEN 'unknown'
        WHEN LOWER(TRIM(Manufacturer)) = 'tidi shield' THEN 'tidi products'
        WHEN LOWER(TRIM(Manufacturer)) = 'terumo i' THEN 'terumo'
        WHEN LOWER(TRIM(Manufacturer)) = 'teleflex medical' THEN 'teleflex'
        WHEN LOWER(TRIM(Manufacturer)) = 'sure step' THEN 'surestep'
        WHEN LOWER(TRIM(Manufacturer)) = 'st jude medical' THEN 'st. jude medical'
        WHEN LOWER(TRIM(Manufacturer)) = 'smiths medical international' THEN 'smiths medical'
        WHEN LOWER(TRIM(Manufacturer)) = 'smiths medical asd, inc.' THEN 'smiths medical'
        WHEN LOWER(TRIM(Manufacturer)) = 'smiths' THEN 'smiths medical'
        WHEN LOWER(TRIM(Manufacturer)) = 'smith medical' THEN 'smiths medical'
		WHEN LOWER(TRIM(Manufacturer)) = 'smith&nephew' THEN 'smiths and nephew'
		WHEN LOWER(TRIM(Manufacturer)) = 'smith & nephew' THEN 'smith and nephew'
		WHEN LOWER(TRIM(Manufacturer)) = 'skylar' THEN 'sklar'
		WHEN LOWER(TRIM(Manufacturer)) = 'sklar sterile' THEN 'sklar'
		WHEN LOWER(TRIM(Manufacturer)) = 'presource standard' THEN 'presource'
		WHEN LOWER(TRIM(Manufacturer)) = 'phillips' THEN 'philips'
		WHEN LOWER(TRIM(Manufacturer)) = 'phasor health' THEN 'phasor'
		WHEN LOWER(TRIM(Manufacturer)) = 'phaser kit' THEN 'phasor'
		WHEN LOWER(TRIM(Manufacturer)) = 'nova plus' THEN 'novaplus'
		WHEN LOWER(TRIM(Manufacturer)) = 'norm-ject' THEN 'normject'
		WHEN LOWER(TRIM(Manufacturer)) = 'none' THEN 'unknown'
		WHEN LOWER(TRIM(Manufacturer)) = 'neoconnect/neomed' THEN 'neomed'
		WHEN LOWER(TRIM(Manufacturer)) = 'molnycke healthcare' THEN 'molnlycke'
		WHEN LOWER(TRIM(Manufacturer)) = 'molynlyckle' THEN 'molnlycke'
		WHEN LOWER(TRIM(Manufacturer)) = 'molnycke' THEN 'molnlycke'
		WHEN LOWER(TRIM(Manufacturer)) = 'molnlycke biogel sensor' THEN 'molnlycke'
		WHEN LOWER(TRIM(Manufacturer)) = 'microtek medical' THEN 'microtek'
		WHEN LOWER(TRIM(Manufacturer)) = 'michigan' THEN 'michigan medicine'
		WHEN LOWER(TRIM(Manufacturer)) = 'mert medical' THEN 'merit medical'
		WHEN LOWER(TRIM(Manufacturer)) = 'medline remedy' THEN 'medline'
		WHEN LOWER(TRIM(Manufacturer)) = 'medi choice' THEN 'medichoice'
		WHEN LOWER(TRIM(Manufacturer)) = 'medical action industries' THEN 'medical action'
		WHEN LOWER(TRIM(Manufacturer)) = 'med choice' THEN 'medchoice'
		WHEN LOWER(TRIM(Manufacturer)) = 'masimoset' THEN 'masimo'
		WHEN LOWER(TRIM(Manufacturer)) = 'masimo set' THEN 'masimo'
		WHEN LOWER(TRIM(Manufacturer)) = 'king system' THEN 'kingsystems'
		WHEN LOWER(TRIM(Manufacturer)) = 'king system' THEN 'kingsystems'
		WHEN LOWER(TRIM(Manufacturer)) = 'kids med brand' THEN 'kids med'
		WHEN LOWER(TRIM(Manufacturer)) = 'kenad sg medical inc' THEN 'kenad sg'
		WHEN LOWER(TRIM(Manufacturer)) = 'in health technology' THEN 'inhealthtechnologies'
		WHEN LOWER(TRIM(Manufacturer)) = 'icumedical' THEN 'icu medical'
		WHEN LOWER(TRIM(Manufacturer)) = 'hollisterwoundcare' THEN 'hollister'
		WHEN LOWER(TRIM(Manufacturer)) = 'greiner' THEN 'greiner bio-one'
		WHEN LOWER(TRIM(Manufacturer)) = 'grinder bio one' THEN 'greiner bio-one'
		WHEN LOWER(TRIM(Manufacturer)) = 'glide scope' THEN 'glidescope'
		WHEN LOWER(TRIM(Manufacturer)) = 'gentherm medical' THEN 'gentherm'
		WHEN LOWER(TRIM(Manufacturer)) = 'fisherbrand' THEN 'fisher brand'
		WHEN LOWER(TRIM(Manufacturer)) = 'ethicon (j&j)' THEN 'ethicon'
		WHEN LOWER(TRIM(Manufacturer)) = 'dukal corporation' THEN 'dukal'
		WHEN LOWER(TRIM(Manufacturer)) = 'dukal corp' THEN 'dukal'
		WHEN LOWER(TRIM(Manufacturer)) = 'dukai' THEN 'dukal'
		WHEN LOWER(TRIM(Manufacturer)) = "dr. brown's medical" THEN 'dr browns'
		WHEN LOWER(TRIM(Manufacturer)) = 'dna genotex' THEN 'dna genotek'
		WHEN LOWER(TRIM(Manufacturer)) = 'derroyal' THEN 'deroyal'
		WHEN LOWER(TRIM(Manufacturer)) = 'de royal industries' THEN 'deroyal'
		WHEN LOWER(TRIM(Manufacturer)) = 'dart jcup' THEN 'dart'
		WHEN LOWER(TRIM(Manufacturer)) = 'cyteir therapeutics' THEN 'cyteir'
		WHEN LOWER(TRIM(Manufacturer)) = 'cratikon' THEN 'critikon'
		WHEN LOWER(TRIM(Manufacturer)) = 'covidien shiley' THEN 'covidien'
		WHEN LOWER(TRIM(Manufacturer)) = 'covidian' THEN 'covidien'
		WHEN LOWER(TRIM(Manufacturer)) = 'coviden' THEN 'covidien'
		WHEN LOWER(TRIM(Manufacturer)) = 'couvidien' THEN 'covidien'
		WHEN LOWER(TRIM(Manufacturer)) = 'cook' THEN 'cook med'
		WHEN LOWER(TRIM(Manufacturer)) = 'con med' THEN 'conmed'
		WHEN LOWER(TRIM(Manufacturer)) = 'centurion medical products corps.' THEN 'centurion'
		WHEN LOWER(TRIM(Manufacturer)) = 'care fusion' THEN 'carefusion'
		WHEN LOWER(TRIM(Manufacturer)) = 'bsn medical' THEN 'bsn'
		WHEN LOWER(TRIM(Manufacturer)) = 'boston' THEN 'boston scientific'
		WHEN LOWER(TRIM(Manufacturer)) = 'bioagiltix' THEN 'bioagilytix'
		WHEN LOWER(TRIM(Manufacturer)) = 'bd alaris' THEN 'bd'
		WHEN LOWER(TRIM(Manufacturer)) = 'bard-parker' THEN 'bard medical'
		WHEN LOWER(TRIM(Manufacturer)) = 'bard parker' THEN 'bard medical'
		WHEN LOWER(TRIM(Manufacturer)) = 'bard access systems' THEN 'bard medical'
		WHEN LOWER(TRIM(Manufacturer)) = 'bard access' THEN 'bard medical'
		WHEN LOWER(TRIM(Manufacturer)) = 'bard' THEN 'bard medical'
		WHEN LOWER(TRIM(Manufacturer)) = 'b braun' THEN 'b braun medical'
		WHEN LOWER(TRIM(Manufacturer)) = 'atrium medical' THEN 'atrium'
		WHEN LOWER(TRIM(Manufacturer)) = 'aspen surgical' THEN 'aspen'
		WHEN LOWER(TRIM(Manufacturer)) = 'arrow international' THEN 'arrow'
		WHEN LOWER(TRIM(Manufacturer)) = 'argon' THEN 'argos'
		WHEN LOWER(TRIM(Manufacturer)) = 'applied med tech' THEN 'applied medical technology'
		WHEN LOWER(TRIM(Manufacturer)) = 'amto' THEN 'amt'
		WHEN LOWER(TRIM(Manufacturer)) = 'amoena?' THEN 'amoena'
		WHEN LOWER(TRIM(Manufacturer)) = 'air life' THEN 'airlife'
		WHEN LOWER(TRIM(Manufacturer)) = 'addto inc' THEN 'addto'
		WHEN LOWER(TRIM(Manufacturer)) = '3m health care' THEN '3m'
        ELSE LOWER(TRIM(Manufacturer))
    END AS Manufacturer_Trimmed,

	CASE
        WHEN LOWER(TRIM(Item)) LIKE '%syringe%' THEN 'syringe'
        WHEN LOWER(TRIM(Item)) LIKE '%needle%' THEN 'needle'
        WHEN LOWER(TRIM(Item)) LIKE '%test tube%' THEN 'test tube'
        WHEN LOWER(TRIM(Item)) LIKE '%sponge%' THEN 'sponges'
		WHEN LOWER(TRIM(Item)) LIKE '%washcloth%' THEN 'wash cloth'
		WHEN LOWER(TRIM(Item)) LIKE '%urine collector%' THEN 'urine collector'
        WHEN LOWER(TRIM(Item)) LIKE '%gauze%' THEN 'gauze'
        WHEN LOWER(TRIM(Item)) = 'unisex swab specimen collection kit for endocervical and male urethral swab specimans' THEN 'unisex swab specimen collection kit for endocervical and male urethral swab specimens'
        WHEN LOWER(TRIM(Item)) LIKE '%uncuffed tracheal tube%' THEN 'uncuffed tracheal tube'
        WHEN LOWER(TRIM(Item)) Like '%granuform dressing%' THEN 'granuform dressing'
        WHEN LOWER(TRIM(Item)) LIKE '%urethral cathater%' THEN 'urethral catheter'
        WHEN LOWER(TRIM(Item)) LIKE '%upep%' THEN 'upep tube'
        WHEN LOWER(TRIM(Item)) LIKE '%securement device%' THEN 'securement device'
        WHEN LOWER(TRIM(Item)) LIKE '%ultrasounds transmission gel%' THEN 'ultrasound transmission gel'
        WHEN LOWER(TRIM(Item)) LIKE '%tube%' THEN 'tube'
        WHEN LOWER(TRIM(Item)) LIKE '%tray%' THEN 'tray'
        WHEN LOWER(TRIM(Item)) LIKE '%transparent film%' THEN 'transparent film'
        WHEN LOWER(TRIM(Item)) LIKE '%tracheal tube%' THEN 'tracheal tube'
        WHEN LOWER(TRIM(Item)) LIKE '%trach tube%' THEN 'tracheal tube'
        WHEN LOWER(TRIM(Item)) LIKE '%tegaderm%' THEN 'tegaderm film'
        WHEN LOWER(TRIM(Item)) LIKE '%surgical pad%' THEN 'surgical pad'
        WHEN LOWER(TRIM(Item)) LIKE '%swab specimens collection kit%' THEN 'swab specimen collection kit'
        WHEN LOWER(TRIM(Item)) LIKE '%suture removal kit%' THEN 'suture removal kit'
        WHEN LOWER(TRIM(Item)) = 'suture' THEN 'sutures'
        WHEN LOWER(TRIM(Item)) LIKE '%surgical glove%' THEN 'surgical gloves'
        WHEN LOWER(TRIM(Item)) LIKE '%surgical drape%' THEN 'surgical drapes'
        WHEN LOWER(TRIM(Item)) LIKE '%surgical cap%' THEN 'surgical caps'
        WHEN LOWER(TRIM(Item)) LIKE '%toothbrush%' THEN 'toothbrush'
        WHEN LOWER(TRIM(Item)) LIKE '%suction catheter%' THEN 'suction catheter'
        WHEN LOWER(TRIM(Item)) LIKE '%steri-strip%' THEN 'steri-strips'
        WHEN LOWER(TRIM(Item)) LIKE '%steri strip%' THEN 'steri-strips'
        WHEN LOWER(TRIM(Item)) LIKE '%towel%' THEN 'towels'
        WHEN LOWER(TRIM(Item)) LIKE '%spring-wire guide%' THEN 'spring wire guide'
        WHEN LOWER(TRIM(Item)) LIKE '%spring wire guide%' THEN 'spring wire guide'
        WHEN LOWER(TRIM(Item)) LIKE '%spray bottle cap%' THEN 'spray bottle caps'
        WHEN LOWER(TRIM(Item)) LIKE '%specimen transport bag%' THEN 'specimen bags'
        WHEN LOWER(TRIM(Item)) LIKE '%specimen bag%' THEN 'specimen bags'
        WHEN LOWER(TRIM(Item)) LIKE '%soap dish%' THEN 'soap dishes'
        WHEN LOWER(TRIM(Item)) LIKE '%smallbore ext. set%' THEN 'smallbore ext set'
        WHEN LOWER(TRIM(Item)) LIKE '%smallbore ext set%' THEN 'smallbore ext set'
        WHEN LOWER(TRIM(Item)) LIKE '%small volumr nebulizer%' THEN 'small volume nebulizer'
        WHEN LOWER(TRIM(Item)) LIKE '%skin protectsnt%' THEN 'skin protectant'
        WHEN LOWER(TRIM(Item)) LIKE '%laryngeal mask%' THEN 'laryngeal mask'
        WHEN LOWER(TRIM(Item)) LIKE '%layngeal mask%' THEN 'laryngeal mask'
        WHEN LOWER(TRIM(Item)) LIKE '%scalpel%' THEN 'scalpel'
        WHEN LOWER(TRIM(Item)) LIKE '%silicone nipple%' THEN 'silicone nipples'
        WHEN LOWER(TRIM(Item)) LIKE '%iv catheter%' THEN 'iv catheter'
        WHEN LOWER(TRIM(Item)) LIKE '%secure all limb holder%' THEN 'secure all limb holder'
        WHEN LOWER(TRIM(Item)) LIKE '%sealable foil bag%' THEN 'sealable bag'
        WHEN LOWER(TRIM(Item)) LIKE '%scrub brush%' THEN 'scrub brush'
        WHEN LOWER(TRIM(Item)) LIKE '%sample collection%' THEN 'sample collection kit'
        WHEN LOWER(TRIM(Item)) LIKE '%salem sump%' THEN 'salem sump'
        WHEN LOWER(TRIM(Item)) LIKE '%safety infusin set%' THEN 'safety infusion set'
        WHEN LOWER(TRIM(Item)) LIKE '%blood collection set%' THEN 'bloot collection set'
        WHEN LOWER(TRIM(Item)) LIKE '%forceps%' THEN 'forceps'
        WHEN LOWER(TRIM(Item)) LIKE '%iv connector%' THEN 'iv connector'
        WHEN LOWER(TRIM(Item)) LIKE '%random bags%' THEN 'bags'
        WHEN LOWER(TRIM(Item)) LIKE '%radial artery cathe%' THEN 'radial artery catheterization set'
        WHEN LOWER(TRIM(Item)) LIKE '%diapers%' THEN 'diapers'
        WHEN LOWER(TRIM(Item)) LIKE '%pump infusion set%' THEN 'pump infusion set'
        WHEN LOWER(TRIM(Item)) LIKE '%pulse oximeter%' THEN 'pulse oximeter'
        WHEN LOWER(TRIM(Item)) LIKE '%pulse ox adhesive%' THEN 'pulse oximeter'
        WHEN LOWER(TRIM(Item)) LIKE '%iodine swabstick%' THEN 'iodine swabsticks'
        WHEN LOWER(TRIM(Item)) LIKE '%underwear%' THEN 'underwear'
        WHEN LOWER(TRIM(Item)) LIKE '%procedure mask%' THEN 'procedure masks'
        WHEN LOWER(TRIM(Item)) LIKE '%probe cover%' THEN 'probe cover'
        WHEN LOWER(TRIM(Item)) LIKE '%extension set%' THEN 'extension set'
        WHEN LOWER(TRIM(Item)) LIKE '%pressure injectable arrow%' THEN 'pressure injectable arrow'
        WHEN LOWER(TRIM(Item)) LIKE '%pressure cuff%' THEN 'pressure cuff'
        WHEN LOWER(TRIM(Item)) LIKE '%underpads%' THEN 'underpads'
        WHEN LOWER(TRIM(Item)) LIKE '%exam glove%' THEN 'exam gloves'
        WHEN LOWER(TRIM(Item)) LIKE '%plastic pipet%' THEN 'pipettes'
        WHEN LOWER(TRIM(Item)) LIKE '%gown%' THEN 'gown'
        WHEN LOWER(TRIM(Item)) LIKE '%pippet%' THEN 'pipettes'
        WHEN LOWER(TRIM(Item)) LIKE '%pipette%' THEN 'pipettes'
        WHEN LOWER(TRIM(Item)) LIKE '%underglove%' THEN 'underglove'
        WHEN LOWER(TRIM(Item)) LIKE '%personal use pack%' THEN 'personal belonging bag'
        WHEN LOWER(TRIM(Item)) LIKE '%cream%' THEN 'cream'
        WHEN LOWER(TRIM(Item)) LIKE '%arm splint%' THEN 'arm splint'
        WHEN LOWER(TRIM(Item)) LIKE '%pca administration kit%' THEN 'pca administration kits'
        WHEN LOWER(TRIM(Item)) LIKE '%slipper%' THEN 'slippers'
        WHEN LOWER(TRIM(Item)) = 'pad' THEN 'pads'
        WHEN LOWER(TRIM(Item)) LIKE '%vial%' THEN 'vials'
        WHEN LOWER(TRIM(Item)) LIKE '%tape%' THEN 'tape'
        WHEN LOWER(TRIM(Item)) LIKE '%scissor%' THEN 'scissors'
        WHEN LOWER(TRIM(Item)) LIKE '%glove%' THEN 'gloves'
        WHEN LOWER(TRIM(Item)) LIKE '%neck brac%' THEN 'neck brace'
        WHEN LOWER(TRIM(Item)) LIKE '%nasopore%' THEN 'nasopore'
        WHEN LOWER(TRIM(Item)) LIKE '%nasopharyngeal temp%' THEN 'nasopharyngeal temperature probe'
        WHEN LOWER(TRIM(Item)) LIKE '%nasal cannula%' THEN 'nasal cannulas'
        WHEN LOWER(TRIM(Item)) LIKE '%nasal divided cannula%' THEN 'nasal cannulas'
        WHEN LOWER(TRIM(Item)) LIKE '%n95%' THEN 'masks'
        WHEN LOWER(TRIM(Item)) LIKE '%mask%' THEN 'masks'
        WHEN LOWER(TRIM(Item)) LIKE '%infusion set%' THEN 'infusion set'
        WHEN LOWER(TRIM(Item)) LIKE '%milk straw%' THEN 'milk straw'
        WHEN LOWER(TRIM(Item)) LIKE '%microtainers%' THEN 'microtainers'
        WHEN LOWER(TRIM(Item)) LIKE '%microscope slide%' THEN 'microscope slides'
		WHEN LOWER(TRIM(Item)) LIKE '%micropuncture int%' THEN 'micropuncture introducer set'
        WHEN LOWER(TRIM(Item)) LIKE '%microinducer kit%' THEN 'micropuncture introducer set'
        WHEN LOWER(TRIM(Item)) LIKE '%microbore infusion set%' THEN 'microbore infusion set'
        WHEN LOWER(TRIM(Item)) LIKE '%feeding adaptor%' THEN 'feeding adaptor'
        WHEN LOWER(TRIM(Item)) LIKE '%leg braces%' THEN 'leg braces'
        WHEN LOWER(TRIM(Item)) LIKE '%medipore%' THEN 'medipore'
        WHEN LOWER(TRIM(Item)) LIKE '%med bag%' THEN 'med bags'
        WHEN LOWER(TRIM(Item)) LIKE '%iv cathater%' THEN 'iv catheter'
        WHEN LOWER(TRIM(Item)) LIKE '%luer lock-to-urethra tip adapter%' THEN 'luer lock adapter'
        WHEN LOWER(TRIM(Item)) LIKE '%luer lock adapter%' THEN 'luer lock adapter'
        WHEN LOWER(TRIM(Item)) LIKE '%low pressure stopcock%' THEN 'low pressure stopcock'
        WHEN LOWER(TRIM(Item)) LIKE '%leg brace%' THEN 'leg braces'
        WHEN LOWER(TRIM(Item)) LIKE '%long thbe%' THEN 'long tube'
        WHEN LOWER(TRIM(Item)) LIKE '%swabs%' THEN 'swabs'
        WHEN LOWER(TRIM(Item)) LIKE '%gene expression collection%' THEN 'gene expression collection'
        WHEN LOWER(TRIM(Item)) LIKE '%tpst pk collection%' THEN 'tpst pk collection'
        WHEN LOWER(TRIM(Item)) LIKE '%biopsy collection%' THEN 'biospy collection'
        WHEN LOWER(TRIM(Item)) = 'jug' THEN 'jugs'
        WHEN LOWER(TRIM(Item)) LIKE '%iv monitoring kit%' THEN 'iv monitoring kit'
        WHEN LOWER(TRIM(Item)) LIKE '%iv administrator%' THEN 'iv administration sets'
        WHEN LOWER(TRIM(Item)) LIKE '%inubating stylet%' THEN 'intubating stylet'
        WHEN LOWER(TRIM(Item)) LIKE '%introducer sheath%' THEN 'introductor sheath'
        WHEN LOWER(TRIM(Item)) LIKE '%insyte autoguard%' THEN 'insyte autoguard'
        WHEN LOWER(TRIM(Item)) LIKE '%insyte-n autoguard%' THEN 'insyte autoguard'
        WHEN LOWER(TRIM(Item)) LIKE '%inelastic wrap%' THEN 'inelastic wrap'
        WHEN LOWER(TRIM(Item)) LIKE '%leg band%' THEN 'leg band'
        WHEN LOWER(TRIM(Item)) LIKE '%pillow%' THEN 'pillow'
        WHEN LOWER(TRIM(Item)) LIKE '%foot brace%' THEN 'foot braces'
        WHEN LOWER(TRIM(Item)) LIKE '%gvl 1 stat%' THEN 'gvl 1 stat'
        WHEN LOWER(TRIM(Item)) LIKE '%guide wire%' THEN 'guide wire'
        WHEN LOWER(TRIM(Item)) = 'guidewire' THEN 'guide wire'
        WHEN LOWER(TRIM(Item)) LIKE '%gravity set%' THEN 'gravity set'
        WHEN LOWER(TRIM(Item)) LIKE '%gravity burette%' THEN 'gravity burette'
        WHEN LOWER(TRIM(Item)) LIKE '%grandfoam silver%' THEN 'granuform dressing'
        WHEN LOWER(TRIM(Item)) LIKE '%graduated nurser%' THEN 'graduated nurser'
        WHEN LOWER(TRIM(Item)) LIKE '%arm sling%' THEN 'arm sling'
        WHEN LOWER(TRIM(Item)) LIKE '%glass slides%' THEN 'microsope slides'
        WHEN LOWER(TRIM(Item)) LIKE '%general purpose temperature pro%' THEN 'temperature probe'
        WHEN LOWER(TRIM(Item)) LIKE '%gel pack%' THEN 'gel packs'
        WHEN LOWER(TRIM(Item)) LIKE '%funnel connector%' THEN 'funnel connector'
        WHEN LOWER(TRIM(Item)) LIKE '%box%' THEN 'boxes'
        WHEN LOWER(TRIM(Item)) LIKE '%forcep%' THEN 'forceps'
        WHEN LOWER(TRIM(Item)) LIKE '%foley catheter%' THEN 'foley catheter'
        WHEN LOWER(TRIM(Item)) LIKE '%flexor check-flo%' THEN 'flexor check flo'
        WHEN LOWER(TRIM(Item)) LIKE '%epidural filter%' THEN 'epidural filter'
        WHEN LOWER(TRIM(Item)) LIKE '%wire guide%' THEN 'wire guide'
        WHEN LOWER(TRIM(Item)) LIKE '%female luer%' THEN 'female luer'
        WHEN LOWER(TRIM(Item)) LIKE '%face shield%' THEN 'face shields'
        WHEN LOWER(TRIM(Item)) LIKE '%abdominal pad%' THEN 'abdominal pads'
        WHEN LOWER(TRIM(Item)) LIKE '%ekg electrod%' THEN 'ekg electrodes'
        WHEN LOWER(TRIM(Item)) LIKE '%ecg tab style%' THEN 'ekg electrodes'
        WHEN LOWER(TRIM(Item)) LIKE '%ecg electrode%' THEN 'ekg electrodes'
        WHEN LOWER(TRIM(Item)) LIKE '%dura-cuf%' THEN 'dura cuffs'
        WHEN LOWER(TRIM(Item)) LIKE '%driveline management sys%' THEN 'driveline management system'
        WHEN LOWER(TRIM(Item)) = 'dressing kit' THEN 'dressing kits'
        WHEN LOWER(TRIM(Item)) LIKE '%dressing change kit%' THEN 'dressing kits'
        WHEN LOWER(TRIM(Item)) LIKE '%drainage system%' THEN 'drainage system'
        WHEN LOWER(TRIM(Item)) LIKE '%drainage and dressing kit%' THEN 'drainage and dressing kit'
        WHEN LOWER(TRIM(Item)) LIKE '%drainage+dressing kit%' THEN 'drainage and dressing kit'
        WHEN LOWER(TRIM(Item)) LIKE '%dna collection kit%' THEN 'dna kits'
        WHEN LOWER(TRIM(Item)) LIKE '%dna saliva kit%' THEN 'dna kits'
        WHEN LOWER(TRIM(Item)) LIKE '%disposable transducer%' THEN 'disposable transducer'
        WHEN LOWER(TRIM(Item)) LIKE '%disposable inner can%' THEN 'disposable inner cannula'
        WHEN LOWER(TRIM(Item)) LIKE '%briefs%' THEN 'briefs'
        WHEN LOWER(TRIM(Item)) LIKE '%cups%' THEN 'cups'
        WHEN LOWER(TRIM(Item)) LIKE '%cup lid%' THEN 'cup lids'
        WHEN LOWER(TRIM(Item)) LIKE '%cotton tip applicators%' THEN 'cotton tipped applicators'
        WHEN LOWER(TRIM(Item)) LIKE '%cotton tipper applicators%' THEN 'cotton tipped applicators'
        WHEN LOWER(TRIM(Item)) LIKE '%cotton tipped applicators%' THEN 'cotton tipped applicators'
        WHEN LOWER(TRIM(Item)) = 'cord' THEN 'cords'
        WHEN LOWER(TRIM(Item)) LIKE '%contact layer%' THEN 'contact layers'
        WHEN LOWER(TRIM(Item)) LIKE '%compression stocking%' THEN 'compression stockings'
        WHEN LOWER(TRIM(Item)) LIKE '%cohesive bandage%' THEN 'cohesive bandages'
        WHEN LOWER(TRIM(Item)) LIKE '%co2 detector%' THEN 'co2 detectors'
        WHEN LOWER(TRIM(Item)) LIKE '%cloth%' THEN 'cloth'
        WHEN LOWER(TRIM(Item)) LIKE '%chloraprep%' THEN 'chloraprep applicator'
        WHEN LOWER(TRIM(Item)) LIKE '%cervical collar%' THEN 'cervical collar'
        WHEN LOWER(TRIM(Item)) = 'catheter' THEN 'catheters'
        WHEN LOWER(TRIM(Item)) = 'catheter (fluid path)' THEN 'catheters'
        WHEN LOWER(TRIM(Item)) LIKE '%bra%' THEN 'bras'
        WHEN LOWER(TRIM(Item)) LIKE '%blood transfer%' THEN 'blood transfer device'
        WHEN LOWER(TRIM(Item)) LIKE '%blood draw kit%' THEN 'blood draw kits'
        WHEN LOWER(TRIM(Item)) LIKE '%blood collection%' THEN 'blood draw kits'
        WHEN LOWER(TRIM(Item)) LIKE '%bedpan%' THEN 'bedpans'
        WHEN LOWER(TRIM(Item)) LIKE '%bandaid%' THEN 'bandaids'
        WHEN LOWER(TRIM(Item)) LIKE '%bandag%' THEN 'bamdages'
        WHEN LOWER(TRIM(Item)) = 'balloon' THEN 'balloons'
        WHEN LOWER(TRIM(Item)) LIKE '%ankle brace%' THEN 'ankle brace'
        WHEN LOWER(TRIM(Item)) LIKE '%ambu bag%' THEN 'ambu bag'
        WHEN LOWER(TRIM(Item)) LIKE '%urethral catheter%' THEN 'urethral catheter'
        WHEN LOWER(TRIM(Item)) LIKE '%plasma sample%' THEN 'plasma samples'
        WHEN LOWER(TRIM(Item)) LIKE '%alcahol swap%' THEN 'alcohol wipes'
        WHEN LOWER(TRIM(Item)) LIKE '%alcohol prep%' THEN 'alcohol wipes'
        WHEN LOWER(TRIM(Item)) LIKE '%alcohol pad%' THEN 'alcohol wipes'
        WHEN LOWER(TRIM(Item)) LIKE '%dipers%' THEN 'diapers'
        WHEN LOWER(TRIM(Item)) LIKE '%suture%' THEN 'sutures'
        ELSE LOWER(TRIM(Item))
    END AS item_display, 
    
    Quantity

FROM
	data.blueprints_inventory
    
WHERE 
    LOWER(TRIM(Manufacturer)) != 'steri strip' AND
    LOWER(TRIM(Manufacturer)) != 'self-cath' AND
    LOWER(TRIM(Manufacturer)) != 'self cath'
    
ORDER BY
	# ordered by manufacturers
	Manufacturer_Trimmed Desc;